import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { PrismaClient } from '@prisma/client';
import { applyWorkspaceSchema } from '../../workspace-schema.mjs';
import { validateDocument } from '../../../../libraries/helpers/src/caleonis/workspace.domain.ts';
import { createWorkspaceRepository, WorkspaceConflict, WorkspaceMissing } from '../../../../libraries/nestjs-libraries/src/caleonis/workspace.repository.ts';
const target=new URL(process.env.DATABASE_URL || 'postgresql://localhost/absent');
if(process.env.CALEONIS_TEST_DB!=='isolated'||!['localhost','127.0.0.1'].includes(target.hostname)||target.pathname!=='/caleonis_workspace_test')throw new Error('Tests require isolated local database');
const db=new PrismaClient(),a=randomUUID(),b=randomUUID(),media=randomUUID();let document;
const settings={schemaVersion:1,imageModelId:'flux-2-pro',videoModelId:'wan-2.2',videoVariantId:'',sizeAspect:'16:9',sizeResolution:'2k',imageFieldValues:{seed:42},videoSettings:{duration:'5',fieldValues:{}}};
const data={prompt:'Produit de test',mode:'image',studioSettings:JSON.stringify(settings),referenceIds:[media]};
const input=()=>validateDocument({kind:'project',title:'Studio persistence test',data});
test.before(async()=>{await applyWorkspaceSchema(db);await db.organization.create({data:{id:a,name:'Studio isolated A'}});await db.organization.create({data:{id:b,name:'Studio isolated B'}});await db.media.create({data:{id:media,name:'Fixture',path:'/fixture.png',organizationId:a}});});
test.after(async()=>{await db.media.deleteMany({where:{organizationId:{in:[a,b]}}});await db.organization.deleteMany({where:{id:{in:[a,b]}}});await db.$disconnect();});
test('real PostgreSQL persists model choices and media ids',async()=>{document=await createWorkspaceRepository(db).create(a,input());const stored=await createWorkspaceRepository(db).get(a,document.id);assert.deepEqual(JSON.parse(stored.data.studioSettings),settings);assert.deepEqual(stored.data.referenceIds,[media]);});
test('new database connection restores the same studio document',async()=>{const other=new PrismaClient();try{const stored=await createWorkspaceRepository(other).get(a,document.id);assert.equal(JSON.parse(stored.data.studioSettings).sizeResolution,'2k');assert.deepEqual(stored.data.referenceIds,[media]);}finally{await other.$disconnect();}});
test('other organization cannot read or overwrite studio configuration',async()=>{const docs=createWorkspaceRepository(db);await assert.rejects(()=>docs.get(b,document.id),WorkspaceMissing);await assert.rejects(()=>docs.save(b,document.id,1,input()),WorkspaceMissing);});
test('concurrent modifications preserve exactly one accepted revision',async()=>{const docs=createWorkspaceRepository(db);const next=input();next.data.mode='video';const results=await Promise.allSettled([docs.save(a,document.id,1,next),docs.save(a,document.id,1,input())]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.ok(results.some(r=>r.status==='rejected'&&r.reason instanceof WorkspaceConflict));});
test('immutable earlier version retains image settings and references',async()=>{const versions=await createWorkspaceRepository(db).versions(a,document.id);assert.equal(versions.length,2);assert.equal(versions[1].data.mode,'image');assert.equal(JSON.parse(versions[1].data.studioSettings).sizeResolution,'2k');assert.deepEqual(versions[1].data.referenceIds,[media]);});
