'use client';
import Link from 'next/link';
import Image from 'next/image';
import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import useSWR from 'swr';
import { useFetch } from '@gitroom/helpers/utils/custom.fetch';
import { useUser } from '@gitroom/frontend/components/layout/user.context';
import { nativeSize, creativeEngine } from '@gitroom/helpers/caleonis/native-image.contract';
import { higgsfieldImage } from '@gitroom/helpers/caleonis/upstream/model-capabilities';
import { PillPopover } from './pill-popover';
import styles from './studio.module.css';

type Doc = { id: string; organizationId: string; title: string; revision: number; data: Record<string, any> };
type Asset = { id: string; path: string; name: string; type?: string };
type Run = { id: string; status: string; engine: string; projectRevision: number; media?: Asset | null; mediaRemoved?: boolean; snapshot: Record<string, any>; usage?: Record<string, number> };
type Capabilities = { dailyLimit: number; native?: { configured: boolean; enabled: boolean; model: string; references: boolean; maxReferences: number } };
const states: Record<string,string> = { submitting:'Demande réservée', queued:'Dans la file', in_progress:'Création en cours', completed:'Terminée', failed:'Demande échouée', unknown:'État à vérifier', cancelled:'Annulée', nsfw:'Demande refusée' };
const pending = ['submitting','queued','in_progress'];
const presets = [
  ['Photo produit', 'Crée une photographie publicitaire de ce produit, fond épuré et lumière de studio. Préserve sa forme, son étiquette et ses proportions.'],
  ['Mise en situation', 'Mets ce produit en situation dans un environnement réaliste adapté à la marque. Préserve exactement son identité.'],
  ['Annonce', 'Crée un visuel de campagne élégant, avec un espace libre pour notre titre et notre offre. Ne crée aucun prix ni promotion fictive.'],
] as const;

/** Staged component: not yet mounted by production routes; tested with isolated fixtures. */
export function CreativeStudio({ documentId }: { documentId?: string }) {
  const api=useFetch(); const user=useUser(); const router=useRouter(); const org=user?.orgId;
  const newDialog=useRef<HTMLDialogElement>(null), mediaDialog=useRef<HTMLDialogElement>(null), historyDialog=useRef<HTMLDialogElement>(null);
  const [draft,setDraft]=useState<Doc|null>(null), [dirty,setDirty]=useState(false), [busy,setBusy]=useState(false);
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[title,setTitle]=useState(''),[search,setSearch]=useState('');
  const [consent,setConsent]=useState(false),[selected,setSelected]=useState(''),[uncertain,setUncertain]=useState('');
  const lock=useRef(false);
  async function request(path:string,method='GET',body?:unknown) {
    const response=await api(path,{method,...(body===undefined?{}:{body:JSON.stringify(body)})});
    const data=await response.json().catch(()=>({}));
    if(!response.ok)throw new Error(typeof data.message==='string'?data.message:'Opération non confirmée. Aucun nouvel achat automatique.');
    return data;
  }
  const projects=useSWR<Doc[]>([org,'studio-projects'],()=>request('/workspace/documents?kind=project'));
  const currentId=documentId||projects.data?.[0]?.id;
  const current=useSWR<Doc>(currentId?[org,'studio-document',currentId]:null,()=>request(`/workspace/documents/${currentId}`));
  const caps=useSWR<Capabilities>([org,'studio-capabilities'],()=>request('/workspace/studio-capabilities'));
  const campaigns=useSWR<Doc[]>([org,'studio-campaigns'],()=>request('/workspace/documents?kind=campaign'));
  const connections=useSWR<Array<{id:string;identifier:string;name:string}>>([org,'studio-connections'],()=>request('/third-party'));
  const media=useSWR<Asset[]>([org,'studio-library',search],()=>request(`/workspace/media?search=${encodeURIComponent(search)}`));
  const versions=useSWR<Array<{revision:number;title:string;data:Record<string,any>}>>(currentId?[org,'studio-history',currentId,draft?.revision]:null,()=>request(`/workspace/documents/${currentId}/versions`));
  const runs=useSWR<Run[]>(currentId?[org,'studio-runs',currentId]:null,()=>request(`/workspace/projects/${currentId}/runs`),{refreshInterval:5000,refreshWhenHidden:false});
  const doc=draft?.organizationId===org?draft:null;
  const referenceIds:string[]=doc?.data.referenceIds||[];
  const references=useSWR<Asset[]>(referenceIds.length?[org,'studio-references',...referenceIds]:null,()=>Promise.all(referenceIds.map(id=>request(`/workspace/media/${id}`))));
  const engine=creativeEngine(doc?.data||{}); const generation=runs.data?.find(run=>run.id===selected)||runs.data?.[0];
  const active=runs.data?.some(run=>pending.includes(run.status)||run.status==='unknown');
  const admin=['ADMIN','SUPERADMIN'].includes(user?.role||'');
  const storageKey=org&&currentId?`caleonis:studio:unconfirmed:${org}:${currentId}`:'';
  useEffect(()=>{setDraft(null);setDirty(false);setConsent(false);setSelected('');setError('');},[org,currentId]);
  useEffect(()=>{if(current.data&&(!draft||current.data.id!==draft.id||current.data.organizationId!==draft.organizationId)){setDraft(current.data);setDirty(false);}},[current.data,draft?.id,org]);
  useEffect(()=>{try{setUncertain(storageKey?sessionStorage.getItem(storageKey)||'':'');}catch{}},[storageKey]);
  useEffect(()=>{if(uncertain&&runs.data?.some(run=>run.id===uncertain)){setUncertain('');try{sessionStorage.removeItem(storageKey);}catch{}}},[runs.data,uncertain,storageKey]);
  useEffect(()=>{if(!dirty)return;const prevent=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[dirty]);
  function navigation(event:React.MouseEvent) { if(dirty&&!window.confirm('Quitter sans enregistrer les modifications ?'))event.preventDefault(); }
  function change(key:string,value:any) { if(!doc)return;setDraft({...doc,data:{...doc.data,[key]:value}});setDirty(true);setConsent(false);setNotice(''); }
  async function act(operation:()=>Promise<void>) { if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await operation();}catch(err){setError(err instanceof Error?err.message:'Opération indisponible.');}finally{lock.current=false;setBusy(false);} }
  async function save() { if(!doc)return;await act(async()=>{const saved=await request(`/workspace/documents/${doc.id}`,'PUT',{kind:'project',title:doc.title,data:doc.data,revision:doc.revision});setDraft(saved);setDirty(false);setConsent(false);await current.mutate(saved,false);await projects.mutate();setNotice(`Version ${saved.revision} enregistrée.`);}); }
  async function create(event:React.FormEvent) { event.preventDefault();await act(async()=>{const saved=await request('/workspace/documents','POST',{kind:'project',title,data:{engine:'native'}});newDialog.current?.close();setTitle('');await projects.mutate();router.push(`/media/studio/${saved.id}`);}); }
  const problem=!doc?'Créez ou ouvrez un projet.':doc.data.mode==='video'?'La génération vidéo sera ajoutée dans un prochain lot.':!admin?'Un administrateur doit autoriser la génération.':dirty?'Enregistrez cette version avant de générer.':!caps.data?.dailyLimit?'Les générations sont désactivées : plafond à configurer.':runs.error||caps.error?'Le suivi ou la configuration est indisponible.':runs.isLoading?'Chargement du suivi…':uncertain?'Envoi non confirmé : vérifiez le suivi avant une nouvelle demande.':active?'Une demande est en cours ou à vérifier.':engine==='native'&&(!caps.data?.native?.configured||!caps.data?.native?.enabled)?'Le moteur natif n’est pas encore activé.':engine==='native'&&(!nativeSize(doc.data.aspectRatio,doc.data.resolution)||referenceIds.length>4)?'Choisissez un format natif et quatre références maximum.':engine==='native'&&referenceIds.length&&!caps.data?.native?.references?'Le stockage actuel ne permet pas encore la retouche native.':engine==='higgsfield'&&(!doc.data.connectionId||referenceIds.length>0)?'Choisissez une connexion Higgsfield ; cet adaptateur n’accepte pas encore les références.':!doc.data.prompt?.trim()?'Décrivez votre création.':'';
  async function generate() { if(!doc||problem||!consent)return;await act(async()=>{const id=crypto.randomUUID();setUncertain(id);try{sessionStorage.setItem(storageKey,id);}catch{}try{const run=await request(`/workspace/projects/${doc.id}/runs`,'POST',{revision:doc.revision,clientRequestId:id,confirmPaidGeneration:true});setSelected(run.id);setUncertain('');try{sessionStorage.removeItem(storageKey);}catch{}setConsent(false);}finally{await runs.mutate();}}); }
  async function runAction(run:Run,action:'sync'|'import') { if(!doc)return;await act(async()=>{await request(`/workspace/projects/${doc.id}/runs/${run.id}/${action}`,'POST');await runs.mutate();await media.mutate();}); }
  const campaign=campaigns.data?.find(item=>item.id===doc?.data.campaignId);
  return <main className={styles.studio}>
    <header className={styles.top}><div className={styles.identity}><span aria-hidden="true" className={styles.mark}>✦</span><div><div className={styles.eyebrow}>Caléonis Marketing</div><h1 className={styles.title}>Studio créatif</h1></div></div><Link href="/media" onClick={navigation} className={styles.secondary}>← Médiathèque</Link></header>
    {(error||projects.error||current.error)&&<div role="alert" className={styles.alert}>{error||'Impossible de charger le projet.'}<button type="button" className={styles.secondary} onClick={()=>void act(async()=>{if(dirty&&!window.confirm('Recharger et abandonner les modifications locales ?'))return;const fresh=await current.mutate();if(fresh){setDraft(fresh);setDirty(false);}await runs.mutate();})}>Recharger</button></div>}
    {notice&&<p role="status" className={styles.notice}>{notice}</p>}
    <div className={styles.layout}>
      <aside className={styles.sidebar}><div className={styles.sideHead}><span className={styles.eyebrow}>Vos projets</span><button type="button" aria-label="Nouveau projet" className={styles.pill} disabled={busy} onClick={()=>{if(!dirty||window.confirm('Quitter sans enregistrer les modifications ?'))newDialog.current?.showModal();}}>＋</button></div><div className={styles.projectList}>{projects.data?.map(item=><Link key={item.id} href={`/media/studio/${item.id}`} onClick={navigation} className={styles.project} aria-current={item.id===currentId?'page':undefined}><strong>{item.title}</strong><small>{item.data.mode==='video'?'Vidéo · préparation':'Image'} · Version {item.revision}</small></Link>)}{projects.isLoading?<p role="status" className={styles.subtle}>Chargement…</p>:!projects.data?.length&&<p className={styles.subtle}>Vos projets et leurs créations resteront accessibles ici.</p>}</div><div className={styles.context}><span className={styles.eyebrow}>Votre environnement</span><Link href="/campaigns" onClick={navigation} className={styles.link}>Campagnes →</Link><Link href="/settings/company" onClick={navigation} className={styles.link}>Entreprise & marque →</Link><Link href="/third-party" onClick={navigation} className={styles.link}>Intégrations →</Link><p className={styles.subtle}>Une seule médiathèque, les mêmes projets pour votre entreprise.</p></div></aside>
      <section className={styles.workspace}>
        <div className={styles.projectHead}>{doc?<input aria-label="Nom du projet" className={styles.name} value={doc.title} maxLength={120} disabled={busy} onChange={event=>{setDraft({...doc,title:event.target.value});setDirty(true);setConsent(false);}}/>:<strong>Votre prochaine création</strong>}<div className={styles.row}><span className={styles.subtle}>{doc?(dirty?'Non enregistré':`Version ${doc.revision} enregistrée`):''}</span>{doc&&<><button className={styles.secondary} type="button" onClick={()=>historyDialog.current?.showModal()}>Historique</button><button className={styles.secondary} type="button" disabled={!dirty||busy} onClick={()=>void save()}>Enregistrer</button></>}</div></div>
        <div className={styles.canvas} aria-label="Aperçu de la création">
          <div className={styles.canvasBadge}><span className={styles.dot}/>{doc?.data.mode==='video'?'Vidéo · préparation':'Image'}{generation?.media?' · Sauvegardée':''}</div>
          {generation?.media?<Image className={styles.image} src={generation.media.path} alt={generation.media.name} width={1024} height={1024} unoptimized/>:generation?<>{pending.includes(generation.status)&&<span className={styles.spinner} aria-hidden="true"/>}<h2 className={styles.canvasTitle}>{states[generation.status]||'Suivi de la création'}</h2><p className={styles.canvasText}>{generation.mediaRemoved?'Ce média a été supprimé de la bibliothèque.':generation.engine==='native'&&pending.includes(generation.status)?'Vous pouvez quitter le studio. Le traitement continue côté serveur.':generation.status==='unknown'?'La réponse du fournisseur doit être vérifiée. Nous ne relançons aucun achat automatiquement.':'Retrouvez les résultats et leurs versions dans ce projet.'}</p>{generation.engine==='higgsfield'&&generation.status==='completed'&&!generation.mediaRemoved&&<button className={styles.primary} type="button" disabled={busy} onClick={()=>void runAction(generation,'import')}>Importer le résultat</button>}</>:<><div className={styles.spark} aria-hidden="true">✧</div><h2 className={styles.canvasTitle}>Du brief à l’image.</h2><p className={styles.canvasText}>Une idée, vos références, votre marque. Créez et retouchez vos visuels sans quitter votre espace marketing.</p><div className={styles.templates}>{presets.map(([label,prompt])=><button type="button" key={label} className={styles.template} disabled={!doc} onClick={()=>change('prompt',prompt)}>{label} ↗</button>)}</div>{!doc&&<button type="button" className={styles.primary} style={{marginTop:20}} onClick={()=>newDialog.current?.showModal()}>Créer un projet</button>}</>}
        </div>
        {generation?.media&&<div className={styles.row} style={{marginTop:10}}><button type="button" className={styles.secondary} onClick={()=>{change('referenceIds',[generation.media!.id]);setSelected('');setNotice('Image ajoutée comme référence. Décrivez la retouche, puis enregistrez.');}}>Retoucher cette image</button><Link className={styles.link} href="/media" onClick={navigation}>Retrouver dans Médias →</Link><span className={styles.subtle}>{generation.engine==='native'?'Moteur natif':'Higgsfield'} · Brief v{generation.projectRevision}</span></div>}
        {doc&&<div className={styles.composer}>
          {referenceIds.length>0&&<div className={styles.references}>{referenceIds.map((id,index)=>{const asset=references.data?.find(item=>item.id===id);return <div className={styles.reference} key={id}>{asset?<Image src={asset.path} width={76} height={76} alt={`Référence ${index+1} : ${asset.name}`} unoptimized/>:<span className={styles.subtle}>Réf. {index+1}</span>}<button type="button" className={styles.remove} aria-label={`Retirer la référence ${index+1}`} onClick={()=>change('referenceIds',referenceIds.filter(value=>value!==id))}>×</button></div>;})}</div>}
          {references.error&&<p role="alert" className={styles.subtle}>Une référence n’est plus disponible ; retirez-la ou choisissez une autre image.</p>}
          <textarea className={styles.prompt} aria-label="Brief créatif" value={doc.data.prompt||''} maxLength={4000} onChange={event=>change('prompt',event.target.value)} placeholder="Décrivez votre image ou les modifications à apporter aux photos de référence…"/>
          <div className={styles.toolbar}><div className={styles.row}>
            <button className={styles.pill} type="button" onClick={()=>mediaDialog.current?.showModal()}>＋ Références {referenceIds.length>0?`(${referenceIds.length})`:''}</button>
            <PillPopover label="Choisir le moteur" trigger={engine==='native'?'✦ Caléonis natif':'Higgsfield'}><label>Moteur<select aria-label="Moteur de génération" value={engine} onChange={event=>{setDraft({...doc,data:{...doc.data,engine:event.target.value,resolution:event.target.value==='native'&&doc.data.resolution==='4k'?'1k':doc.data.resolution}});setDirty(true);setConsent(false);}}><option value="native">Caléonis natif · OpenAI</option><option value="higgsfield">Higgsfield · app externe</option></select></label>{engine==='native'?<p className={styles.subtle}>{caps.data?.native?.model||'Configuration en cours'} · fournisseur côté serveur. Aucun compte Higgsfield requis.</p>:<label>Compte connecté<select aria-label="Compte Higgsfield" value={doc.data.connectionId||''} onChange={event=>change('connectionId',event.target.value)}><option value="">Choisir dans Intégrations</option>{connections.data?.filter(item=>item.identifier==='higgsfield').map(item=><option value={item.id} key={item.id}>{item.name||'Higgsfield'}</option>)}</select><Link href="/third-party" className={styles.link} onClick={navigation}>Gérer les intégrations →</Link></label>}</PillPopover>
            <PillPopover label="Réglages de l’image" trigger={`${doc.data.aspectRatio||'1:1'} · ${engine==='native'?nativeSize(doc.data.aspectRatio,doc.data.resolution)||'Format à adapter':doc.data.resolution?.toUpperCase()}`}><label>Format<select aria-label="Format de l’image" value={doc.data.aspectRatio||'1:1'} onChange={event=>change('aspectRatio',event.target.value)}>{higgsfieldImage.aspect_ratio&&higgsfieldImage.aspect_ratio.options?.map(([label,value])=><option key={value} value={value}>{label} · {value}</option>)}</select></label><label>Dimensions<select aria-label="Dimensions de l’image" value={doc.data.resolution||'1k'} onChange={event=>change('resolution',event.target.value)}>{(engine==='native'?['1k','2k']:['1k','2k','4k']).map(value=><option key={value} value={value}>{engine==='native'?nativeSize(doc.data.aspectRatio,value):value.toUpperCase()}</option>)}</select></label>{engine==='native'&&<label>Qualité<select aria-label="Qualité de l’image" value={doc.data.quality||'medium'} onChange={event=>change('quality',event.target.value)}><option value="low">Brouillon</option><option value="medium">Standard</option><option value="high">Haute qualité</option></select></label>}</PillPopover>
            <PillPopover label="Contexte de campagne" trigger={campaign?'Campagne liée':'＋ Campagne'}><label>Campagne<select aria-label="Campagne associée" value={doc.data.campaignId||''} onChange={event=>change('campaignId',event.target.value)}><option value="">Création indépendante</option>{campaigns.data?.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><p className={styles.subtle}>Le moteur natif utilise le brief, l’offre et les règles de marque de cette campagne. Leur version est conservée avec le rendu.</p></PillPopover>
          </div><button className={styles.primary} type="button" disabled={busy||!!problem||!consent||!!references.error} onClick={()=>void generate()}>✦ Générer cette version</button></div>
          <label className={styles.consent}><input type="checkbox" checked={consent} disabled={busy||!!problem} onChange={event=>setConsent(event.target.checked)}/><span>J’autorise l’envoi du brief{engine==='native'?', du contexte de marque et des références à OpenAI':' à Higgsfield'} et les frais du fournisseur. Je dispose des droits nécessaires. {engine==='native'?'Le résultat sera enregistré dans la médiathèque.':'Les frais utilisent le compte API connecté.'} Aucune publication automatique.</span></label>
          <p className={styles.subtle} role="status">{problem||`${engine==='native'?'Retouche sur références disponible.':'Création depuis le texte uniquement.'} Le coût dépend du modèle, des dimensions et des références ; le plafond actuel compte les demandes, pas les euros.`}</p>
          {uncertain&&<button type="button" className={styles.secondary} onClick={()=>void act(async()=>{await runs.mutate();setNotice('Historique relu. Si la demande reste absente, ne créez pas de doublon ; une vérification serveur est nécessaire.');})}>Vérifier le suivi de l’envoi</button>}
        </div>}
        <div className={styles.sectionHead}><h2>Créations du projet <span className={styles.subtle}>· {runs.data?.length||0}</span></h2><button className={styles.pill} type="button" disabled={busy} onClick={()=>{if(generation&&!generation.media)void runAction(generation,'sync');else void act(async()=>{await runs.mutate();});}}>Actualiser</button></div>
        {runs.error?<p role="alert" className={styles.alert}>Le suivi ne peut pas être chargé.</p>:!runs.data?.length?<div className={styles.empty}>Vos créations apparaîtront ici, avec le moteur et la version du brief utilisés.</div>:<div className={styles.results}>{runs.data.map(run=><button type="button" key={run.id} className={styles.result} aria-pressed={generation?.id===run.id} onClick={()=>setSelected(run.id)}><div className={styles.thumbnail}>{run.media?<Image src={run.media.path} alt={run.media.name} width={220} height={140} unoptimized/>:states[run.status]||run.status}</div><div className={styles.resultInfo}><strong>Version {run.projectRevision} · {states[run.status]}</strong>{run.engine==='native'?'Caléonis natif':'Higgsfield'} · {run.snapshot._size||run.snapshot.aspectRatio}</div></button>)}</div>}
      </section>
    </div>
    <dialog ref={newDialog} className={styles.dialog} aria-labelledby="studio-new-title"><form onSubmit={create}><div className={styles.dialogHead}><h2 id="studio-new-title">Nouveau projet créatif</h2><button className={styles.pill} aria-label="Fermer" type="button" onClick={()=>newDialog.current?.close()}>×</button></div><label>Nom du projet<input required maxLength={120} value={title} onChange={event=>setTitle(event.target.value)} placeholder="Ex. Lancement de notre nouvelle offre"/></label><p className={styles.subtle}>Créer un projet ne commande aucune génération.</p>{error&&<p role="alert" className={styles.alert}>{error}</p>}<button className={styles.primary} type="submit" disabled={busy||!title.trim()}>Créer le projet</button></form></dialog>
    <dialog ref={mediaDialog} className={styles.dialog} aria-labelledby="studio-media-title"><div className={styles.dialogHead}><h2 id="studio-media-title">Vos images de référence</h2><button className={styles.pill} aria-label="Fermer" type="button" onClick={()=>mediaDialog.current?.close()}>×</button></div><p className={styles.subtle}>Quatre références maximum pour le moteur natif. PNG, JPEG ou WebP, 10 Mo par fichier, 20 Mo au total. La première image sert de référence principale.</p><label>Rechercher<input maxLength={120} value={search} onChange={event=>setSearch(event.target.value)} placeholder="Nom d’un média…"/></label><div className={styles.mediaGrid}>{media.data?.filter(item=>item.type==='image').map(item=><button type="button" key={item.id} className={styles.mediaOption} aria-pressed={referenceIds.includes(item.id)} disabled={!referenceIds.includes(item.id)&&referenceIds.length>=4} onClick={()=>change('referenceIds',referenceIds.includes(item.id)?referenceIds.filter(id=>id!==item.id):[...referenceIds,item.id])}><Image src={item.path} alt={item.name} width={150} height={110} unoptimized/><span>{referenceIds.includes(item.id)?'✓ ':''}{item.name}</span></button>)}</div>{media.error&&<p role="alert" className={styles.alert}>La médiathèque est indisponible.</p>}<div className={styles.row}><Link href="/media" onClick={navigation} className={styles.secondary}>Importer dans Médias</Link><button className={styles.primary} type="button" onClick={()=>mediaDialog.current?.close()}>Utiliser la sélection</button></div><p className={styles.subtle}>Les 40 médias récents correspondant à la recherche sont affichés.</p></dialog>
    <dialog ref={historyDialog} className={styles.dialog} aria-labelledby="studio-history-title"><div className={styles.dialogHead}><h2 id="studio-history-title">Versions du projet</h2><button className={styles.pill} aria-label="Fermer" type="button" onClick={()=>historyDialog.current?.close()}>×</button></div>{versions.data?.map(version=><div className={styles.version} key={version.revision}><div><strong>Version {version.revision}</strong><p className={styles.subtle}>{version.title}</p></div><button type="button" className={styles.secondary} disabled={busy||!doc} onClick={()=>{if(!doc)return;setDraft({...doc,title:version.title,data:version.data});setDirty(true);setConsent(false);historyDialog.current?.close();setNotice('Version reprise comme brouillon. Enregistrez pour créer une nouvelle version.');}}>Reprendre</button></div>)}{versions.error&&<p role="alert">Historique indisponible.</p>}</dialog>
  </main>;
}
